# -*- coding: utf-8 -*-
"""Sprint 2.22.0b.140 — «الأحافير الإنجليزية المرئية» (visible EN fossils).

Isolated E14 test: reads the REAL index.html + evaluate_unified.py (not mocks) and
asserts the value-neutral frontend localization:
  (1) copyResult() fully wrapped in t()/pick() (was 100% hardcoded Arabic) + the
      `المنهجية` brace-bug fixed (previously pushed "المنهجية: undefined" on refusals).
  (2) raw `_ar` reads that ignore an existing twin/catalog swapped to pick():
      rics note, scope disclaimer, requires_user_input, freshness caveat, landmark
      name, corner/HBU evidence, trend historical_window.
  (3) TREND_LABEL_EN map + trLabel() localize the raw trend label.
  (4) cap-rate gloss wrapped in t().
  (5) version bump; AR byte-identical (every AR literal survives as the t() first
      arg / pick returns _ar in AR mode) — engine valuation logic untouched.
"""
import io, re, sys

ROOT = r"C:\Thammen\deploy v2"
HTML = io.open(ROOT + r"\index.html", encoding="utf-8").read()
ENG  = io.open(ROOT + r"\evaluate_unified.py", encoding="utf-8").read()

passed = 0
failed = 0
def ck(name, cond):
    global passed, failed
    if cond:
        passed += 1
        print("  PASS", name)
    else:
        failed += 1
        print("  FAIL", name)

print("Sprint 2.22.0b.140 — visible EN fossils\n")

# ── (1) copyResult fully localized ──────────────────────────────────────────
print("[copyResult]")
ck("header t()",        "t('━━━ تقرير ثمّن ━━━','━━━ Thammen report ━━━')" in HTML)
ck("address label t()", "t('العنوان: ','Address: ')" in HTML)
ck("value label t()",   "t('قيمة التقييم السوقي: ','Market valuation: ')" in HTML)
ck("range label t()",   "t('النطاق: ','Range: ')" in HTML)
ck("n label t()",       "t('عدد الصفقات المقارِنة: ','Comparable transactions: ')" in HTML)
ck("honesty line t()",  "t('تقييم سوقيّ آليّ، وليس تقييماً معتمداً.','Automated market valuation — not a certified valuation.')" in HTML)
ck("footer line t()",   "t('— مُولَّد من ثمّن (thammen.qa)','— Generated by Thammen (thammen.qa)')" in HTML)
ck("methodology via pick", "t('المنهجية: ','Methodology: ')+pick(d,'methodology')" in HTML)
ck("reason via pick",      "t('ملاحظة: ','Note: ')+pick(v,'reason')" in HTML)
ck("latest_record via pick","pick(_df,'latest_record')" in HTML)
ck("asset label ASSET_EN", "t(ASSET_AR[d.asset_type]||d.asset_type,ASSET_EN[d.asset_type]||d.asset_type)" in HTML)
ck("copy button label t()","t('نسخ النتيجة','Copy result')" in HTML)
# the brace bug: methodology block now fully guarded (was `if(...)push('');push('المنهجية...')`)
ck("methodology brace fixed", "if(d.methodology_ar){lines.push('');lines.push(t('المنهجية: '" in HTML)
# old hardcoded fossils are GONE
ck("old address fossil gone",   "lines.push('العنوان: '+d.address)" not in HTML)
ck("old value fossil gone",     "lines.push('قيمة التقييم السوقي: '+fmt(v.amount)+' ر.ق')" not in HTML)
ck("old honesty fossil gone",   "lines.push('تقييم سوقيّ آليّ، وليس تقييماً معتمداً.')" not in HTML)

# ── (2) pick() swaps for existing twins/catalog ─────────────────────────────
print("[pick swaps]")
ck("rics note pick",       "'+pick(d,'rics_methodology_note')+'</div>'" in HTML)
ck("rics note raw gone",   "'+d.rics_methodology_note_ar+'</div>'" not in HTML)
ck("scope disclaimer pick","'+pick(ss,'disclaimer')+'</div>'" in HTML)
ck("scope disclaimer raw gone", "'+ss.disclaimer_ar+'</div>'" not in HTML)
ck("requires pick",        "'</strong> '+pick(ss,'requires_user_input')+'</div>'" in HTML)
ck("caveat pick (foot)",   "'<div class=\"dfc s-'+sev+'\">'+pick(d.data_freshness,'caveat')+'</div>'" in HTML)
ck("landmark name pick",   "label:pick(m,'name')+' — '+m.distance_m" in HTML)
ck("landmark name raw gone","label:m.name_ar+' — '+m.distance_m" not in HTML)
ck("corner evidence pick", "label:pick(ca,'evidence')" in HTML)
ck("hbu evidence pick",    "label:pick(hbu,'evidence')" in HTML)
ck("historical_window pick","' — '+pick(tr,'historical_window')" in HTML)

# ── (3) trend label map ─────────────────────────────────────────────────────
print("[trend label]")
ck("TREND_LABEL_EN map",   "var TREND_LABEL_EN=" in HTML and "'ارتفاع':'Rising'" in HTML and "'متذبذب':'Volatile'" in HTML)
ck("trLabel fn",           "function trLabel(s){return (LANG==='en'&&s&&TREND_LABEL_EN[s])" in HTML)
ck("headline uses trLabel", "t('اتجاه السوق: ','Market trend: ')+trLabel(tr.label||'')" in HTML)
ck("pill uses trLabel",    "esc(trLabel(_tl))" in HTML)
ck("color regex still on _tl", "const _tl=tr.label||''" in HTML)  # color logic keyed on AR label, unchanged

# ── (4) cap-rate gloss ──────────────────────────────────────────────────────
print("[cap-rate gloss]")
ck("gloss t()", "t('معدّل الرسملة: نسبة صافي الدخل السنويّ إلى قيمة العقار (الطبيعيّ في قطر 5–6%).','Capitalization rate: the ratio of annual net income to the property value (typically 5–6% in Qatar).')" in HTML)
ck("gloss raw gone", ">معدّل الرسملة: نسبة صافي الدخل السنويّ إلى قيمة العقار (الطبيعيّ في قطر 5–6%).</div>" not in HTML)

# ── (5) version + AR byte-identical guardrails + value-neutrality ────────────
print("[version + value-neutral]")
ck("engine version b140", "thammen-sprint2p22p0b140-en-visible-fossils" in ENG)
ck("sprint tag b140",     "SPRINT_TAG = '2.22.0b.140'" in ENG)
# AR survives (t() first-arg / pick returns _ar): the original Arabic literals still present
ck("AR literal survives (value)", "'قيمة التقييم السوقي: '" in HTML)
ck("AR literal survives (honesty)","'تقييم سوقيّ آليّ، وليس تقييماً معتمداً.'" in HTML)
ck("AR literal survives (gloss)",  "'معدّل الرسملة: نسبة صافي الدخل السنويّ إلى قيمة العقار (الطبيعيّ في قطر 5–6%).'" in HTML)
# the localization helpers exist (value-neutral display only)
ck("t() helper intact",    "function t(ar,en){return (LANG==='en'&&en!=null)?en:ar;}" in HTML)
ck("pick() helper intact", "function pick(o,base){" in HTML)
# no NEW engine valuation logic (only the 2 version-string lines changed in the engine)
ck("engine amount/method not in this sprint's copy edits", "def copyResult" not in ENG)

print("\n%d passed, %d failed" % (passed, failed))
sys.exit(1 if failed else 0)
